language: node_js
node_js:
- '10'

before_install:
- npm install -g @angular/cli
install: npm install

branches:
  only:
  - main
  
deploy:
  provider: heroku
  app: jira-app-ak
    api_key:
    secure: NVmpZ/vjMQBjXuvgj4GfR63J7tKAeU5hQ13EmTapp1PtYeY4ZVAVzElsmQkfF9/2BzWpvCS2t3pmatqltgb3EpJAqidfLOtk76EykyTpGGcAnnv+jP9VnrWj//bFE4SCIReLe6gQ7sNbo3ydws28L6Kq3GEo8rDUoU00xIKpcxAGePqcdle7Xd3Blwy1txZ6kyy7sPO9tnDMe3Jaa562IrPfl33Ghmzf68xy2xnwKXUt/tZ0W+qxWjrothSBjFqKOSBNFZIpKpGoNCXCDNVBRfJYSHy6DpAgLR1dCns22yXScB2X8/N/eSkQF37hfeqYMAzZs8aPXgbOjGTHxUR9mjQOovVAiXTleIg4tt7aN4P6ZnvwZdHV86YD1v/+ArgL/mfGLbbWHed1YDzmXX5EcEiUT4m0QnPfH2qK7PAWErPAbAYawSRQZYgu3rFHtxwr0oK/sXZN8EfBCq4fRluBuUQ840hPXAb2Qc9q18pZGtX+HIuCt38dVYLmezjzvaSi54vH2PQrFjCyxpZDDmeLUSDL400Z8vzufbfjM5GszDMhUecb9Y+HQG1tBllEL7hkIu4nIxqNq9dXoF12gCqJRsJdP1zbuFpdKb9oqCjjJhQfoRcg/hOxWh9MhlCcReDnoMb6c5BLgB+Lqv8abk8oRJ68WjsQZNNmNiP4hgDfGnU=
